Parse event type
Crazymax11/vue-metainfo-loader pull request #2
Opened 2018-12-18 09:29 UTC by norvele

2018-12-18 16:25 UTC, Crazymax11 commented on tests/fixtures/eventsWithTypes.js
> +                type: {
AST ноды в выходе - отстой. Для таких случаев я бы ожидал что type будет ChangeEvent

2018-12-18 16:35 UTC, Crazymax11 requested changes
Конский ПР из-за рефакторинга.
Это вот то, о чем обычно говорит Глеб - большой ПР в котором не так много функциональных правок но смотреть нереально сложно

2018-12-18 16:35 UTC, Crazymax11 commented on tests/test.js
> +        expect(parseComponentCode(code).comments).toEqual(eventsWithTypesFixture);
я бы ожидал что в events, а не в comments, будут перечислены события из jsdoc'ов

2018-12-18 16:35 UTC, Crazymax11 commented on index.js
> +    const result = tag.description.match(reg);
тут деструктуризацию можно
```js
const [name = '', , typeString = '',, description = ''] = tag.description.match(reg);
```

а ещё match может вернуть `null` и этот код развалится

если тебе не нужны 2 и 4 сопоставления, можно использовать non capturing group через `?:` синтаксис
подробнее [тут](https://stackoverflow.com/questions/3512471/what-is-a-non-capturing-group-what-does-do) и [тут](https://www.stefanjudis.com/today-i-learned/non-capturing-groups-in-regular-expressions/)

```js
const reg = /(\w+)(?:\s+(\{.*\}))?(?:\s+-?\s?(.*))?/;
```

а ещё напиши комментарием что ты пытаешься захватить тут регекспом. Пока мы в пул реквесте - более менее понятно, когда вольем - станет непонятно. 
Вообще, правило хорошего тона - комментировать любой regexp, сложнее чем `word1|word2`

2018-12-18 16:35 UTC, Crazymax11 commented on index.js
> + * Parse and enrich emits or fires tag
jsdoc можно пообъемней
парсим тэги emits и fires, парсим тип события и описания события

2018-12-18 16:35 UTC, Crazymax11 commented on index.js
> +        return ['emits', 'fires'].indexOf(tag.title) > -1 ? enrichEmitsTag(tag) : tag;
коммент почему именно эти 2
indexOf => includes

2018-12-19 12:11 UTC, norvele commented on tests/fixtures/eventsWithTypes.js
> +                type: {
Ну тут либо возвращаемся к предыдущему ПР, там где я предлагал возвращать не доктриновский AST, а уже свою структуру, либо пока оставляем тут AST. Ну типо тут и так AST, я просто в нем допарсил тэги с эмитами, тут какраз таки странно было бы не сделать AST.

2018-12-19 12:13 UTC, norvele commented on tests/test.js
> +        expect(parseComponentCode(code).comments).toEqual(eventsWithTypesFixture);
Ну да, в events тоже надо докинуть, по типу как ты с type для props сделал. Но это мало нам инфы о типе дает, там будет например какойнить "ChangeEvent" и все, непонятно чо с ним делать, из чего он состоит

2018-12-19 12:16 UTC, norvele commented on index.js
> +    const result = tag.description.match(reg);
По ES6+ - нам же тогда надо будет бабель? Или мы не будем собирать? Про "non capturing group" огонь, забыл что такое есть. Регекспу откоменчу

2018-12-19 12:18 UTC, norvele commented
Коммит с рефакторингом тестов уберу пока, потом докачу вторым ПР

2018-12-22 17:15 UTC, Crazymax11 commented on tests/test.js
> +        expect(parseComponentCode(code).comments).toEqual(eventsWithTypesFixture);
Ну это уже отдельным шагом можно. Сначала какую нибудь инфу, потом инфу поточнее

2018-12-22 17:16 UTC, Crazymax11 commented on index.js
> +    const result = tag.description.match(reg);
> По ES6+ - нам же тогда надо будет бабель? 

Нет, пишем код под node.js 8+. Там поддерживается весь ES6, ES7 и частично ES8.
Если тесты выполняются, значит ты написал нормальный код ;)

2018-12-26 07:31 UTC, Crazymax11 commented on tests/fixtures/eventsWithTypes.js
> +                type: {
имхо надо от AST уходить где это возможно, но это уже на будущее

2018-12-26 07:32 UTC, merged

2018-12-26 07:43 UTC, Crazymax11 commented on index.js
> +    const result = tag.description.match(reg);
Присмотрелся, тебе и non capturing не нужен, `\s+` можно вынести за скобки как `\s*` и группы лишние отпадут